name: Update books and articles
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: zwacky/goodreads-profile-workflow@a1b8b48b991987cb356422d51fcc91a81a2b6e26 # v1.2.4
        with:
          goodreads_user_id: "29398258"
          template: "- [$title]($url) by $author (⭐️$average_rating)"
          sort_by_fields: "<user_date_added"
      - uses: sarisia/actions-readme-feed@bdde7fdb36e19b030b77cf1f7b7f09db68219f32 # v1.10.1
        id: feed
        with:
          file: 'README.md'
          format: '- ${day} ${monthlong} - [${title}](${url})'
          timezone: 'Europe/London'
          url: |
            https://blog.jakelee.co.uk/feed.xml
            https://history.jakelee.co.uk/feed.xml
            https://minima.jakelee.co.uk/feed.xml
            https://fragments.jakelee.co.uk/feed.xml
            https://jakelee.co.uk/feed.xml
            https://news.codecured.org/feed.xml
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@266e3281638e11cf0101ae9c3e893e8abfc6fda1 # latest as of 2024-08-16
        with:
          name: GitHub Actions
          email: actions@github.com
          message: Updates article list
